[build]
  command = "echo 'No build for this site'"

[dev]
  command = ""

# Catch-all for any unfound short codes
[[redirects]]
  from = "*"
  to = "https://www.theunitedeffort.org/"
  status = 302

