[build]
  command = "npm run build"
  publish = "./dist"

[dev]
  command = ""
  publish = "./dist"

# Catch-all for any unfound short codes
[[redirects]]
  from = "*"
  to = "https://www.theunitedeffort.org/"
  status = 302

